version: '3.9'

services:
  db:
    container_name: postgresql
    image: postgres:15-alpine
    volumes:
      - ${HOME}/customer-inquiry-system/data/postgresql:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_DB: "inquirysystem"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: Asia/Seoul
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
      timeout: 120s
    networks:
      - inquirysystem-network

networks:
  inquirysystem-network:
    driver: bridge
